version: 2.1
orbs:
  gcp-gke: circleci/gcp-gke@0.2.0
  gcr: circleci/gcp-gcr@0.0.2
  k8s: circleci/kubernetes@0.1.0

commands:
  install:
    description: "Install `gcloud` and `kubectl` if not already installed."
    steps:
      - gcloud/install
      - k8s/install
  init:
    description: "Initialize the `gcloud` CLI."
    steps:
      - gcloud/initialize

jobs:
  gke-deploy:
    docker:
      - image: google/cloud-sdk
    resource_class: medium
    steps:
      - checkout
      - run: 
          name: Setup Google Cloud SDK
          command: |
            pwd
            apt-get install -qq -y gettext
            echo ${GCLOUD_SERVICE_KEY} > key.json
            gcloud auth activate-service-account --key-file=key.json
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
            gcloud --quiet container clusters get-credentials ${GOOGLE_CLUSTER_NAME}
      - run:
          name: kubectl get pods
          command: |
            kubectl get pods
      - run:
          name: kubectl apply
          command: |
            kubectl apply -f deployment.yaml

workflows:
  version: 2
  gke_deploy:
    jobs:
      - gke-deploy
