version: 2.1
orbs:
  gcp-gke: circleci/gcp-gke@0.2.0
  gcr: circleci/gcp-gcr@0.0.2
  k8s: circleci/kubernetes@0.1.0

commands:
  install:
    description: "Install `gcloud` and `kubectl` if not already installed."
    steps:
      - gcloud/install
      - k8s/install
  init:
    description: "Initialize the `gcloud` CLI."
    steps:
      - gcloud/initialize

jobs:
  kubectl:
    docker:
      - image: google/cloud-sdk
    resource_class: medium
    environment:
      - PROJECT_NAME: "my-app"
      - GOOGLE_PROJECT_ID: "${GOOGLE_PROJECT_ID}"
      - GOOGLE_COMPUTE_ZONE: "${GOOGLE_COMPUTE_ZONE}"
      - GOOGLE_CLUSTER_NAME: "preprod-cooptalis-dataplatform"
    steps:
      - checkout
      - run: 
          name: Setup Google Cloud SDK
          command: |
            pwd
            apt-get install -qq -y gettext
            echo "gcloud key"
            echo ${GCLOUD_SERVICE_KEY} > key.json
            echo "gcloud auth"
            gcloud auth activate-service-account --key-file=key.json
            echo "gcloud config project"
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            echo "gcloud config zone"
            gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
            echo "gcloud get-creds"
            gcloud --quiet container clusters get-credentials ${GOOGLE_CLUSTER_NAME}
      - setup_remote_docker
      - run:
          name: kubectl get pods
          command: |
            kubectl get pods

workflows:
  version: 2
  germain_test:
    jobs:
      - kubectl
